#!/bin/bash

# List of Executables; Total Number; Execution Directory;
BIN_LIST=$(file * | grep ELF | cut -f1 -s -d":" | tee tmp)
TOTAL_BIN=$(wc -l tmp | cut -f1 -d" " && rm tmp)
BIN_DIR=$(pwd)

# List Binaries

# Delete Binaries
echo -e $"\n Removing ..."
for binary in $BIN_LIST
do
        echo -e $"\t$binary"
        rm -f $binary
done

echo -e $"\n $TOTAL_BIN binary(s) in $BIN_DIR\n"
